# Generated by Django 6.0.7 on 2026-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_main', '0004_product_color_product_size_product_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.TextField()),
                ('sity', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=400)),
                ('telepfone', models.IntegerField()),
                ('acca', models.BooleanField(default=False)),
            ],
        ),
    ]
