# Generated by Django 6.0.7 on 2026-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_main', '0005_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
