# Generated by Django 6.0.7 on 2026-07-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_main', '0006_checkout_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='catigorya',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='catigorya',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='catigorya',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
