# Generated by Django 6.0.7 on 2026-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_main', '0007_catigorya_name_en_catigorya_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='adres_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='adres_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='adres_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='country_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='country_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='country_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='first_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='first_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='first_name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='last_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='last_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='last_name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='sity_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='sity_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='sity_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='zip_code_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='zip_code_ru',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='zip_code_uz',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
