# Generated by Django 6.0.7 on 2026-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_main', '0008_checkout_adres_en_checkout_adres_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ism', models.CharField(max_length=200)),
            ],
        ),
    ]
