# Generated by Django 6.0.7 on 2026-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_main', '0009_tek'),
    ]

    operations = [
        migrations.AddField(
            model_name='tek',
            name='ism_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tek',
            name='ism_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tek',
            name='ism_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tek',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tek',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tek',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
